site_name: CraneMagic 文档 | Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html

nav:
  - 介绍: index.md
  - 设计:
    - 整体架构: design/arch.md
  - 技术细节:
    - 通用组件:
      - WebAPI: tech_details/common/cranemagic-service-webapi.md
  - 更新日志: updates.md
  - MkDocs: mkdocs.md
  

plugins:
  - search
  - git-revision-date-localized

extra_css:
  - stylesheets/extra.css
