site_name: CraneMagic 文档 | Docs
theme:
  name: material

nav:
  - 介绍: index.md
  - 设计:
    - 整体架构: design/arch.md
  - 更新日志: updates.md
  - MkDocs: mkdocs.md
  

plugins:
  - search
  - git-revision-date-localized

extra_css:
  - stylesheets/extra.css
